# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {Common 17-41} -limit 10000000
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7z010clg400-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /auto/homes/hc475/P35/rtl/matS/matS.cache/wt [current_project]
set_property parent.project_path /auto/homes/hc475/P35/rtl/matS/matS.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo /auto/homes/hc475/P35/rtl/matS/matS.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  /auto/homes/hc475/P35/rtl/src/src/p_multiplier.v
  /auto/homes/hc475/P35/rtl/src/src/multiple_mat.v
  /auto/homes/hc475/P35/rtl/src/src/TB.v
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}

synth_design -top Mat_mul_TB -part xc7z010clg400-1


write_checkpoint -force -noxdef Mat_mul_TB.dcp

catch { report_utilization -file Mat_mul_TB_utilization_synth.rpt -pb Mat_mul_TB_utilization_synth.pb }
